language: node_js
node_js:
  - "12"

script:
  - npm run lint
  - npm run build

  # Move main JS file to a static name
  # - npm run check-size
  # Disabled 2022-12-23 because Travis started getting a 401 trying to post back
  # the bundle size stats.
