<?php
/**
 * Improve compatibility between H2 and various WP plugins.
 */

namespace H2\Compat;

use GFCommon;
use GFFormDisplay;
use GFFormsModel;

/**
 * Bootstrap compatibility support helpers.
 */
function bootstrap() {
	bootstrap_gravityforms();
	add_action( 'render_block', __NAMESPACE__ . '\\render_todo_list_block', 10, 2 );
}

/**
 * Bootstrap Gravity Forms support.
 */
function bootstrap_gravityforms() {
	if ( ! class_exists( '\\GFCommon' ) ) {
		return;
	}

	add_action( 'template_redirect', __NAMESPACE__ . '\\handle_gravityform_request' );
	add_filter( 'gform_shortcode_form', __NAMESPACE__ . '\\filter_gravityform_shortcode', 10, 2 );
}

/**
 * Filter the [gravityform] shortcode to replace with an iframe.
 *
 * @param string $html       HTML generated by Gravity Forms
 * @param array  $attributes Attributes passed to the shortcode
 * @return string iframe tag
 */
function filter_gravityform_shortcode( $html, $attributes ) {
	$attrs = shortcode_atts(
		[
			'id' => 0,
			'title' => 'true',
			'description' => 'true',
		],
		$attributes,
		'gravityforms'
	);

	$url = add_query_arg( 'h2_gravityform', absint( $attrs['id'] ), home_url() );
	if ( $attrs['title'] === 'true' ) {
		$url = add_query_arg( 'title', '1', $url );
	}
	if ( $attrs['description'] === 'true' ) {
		$url = add_query_arg( 'description', '1', $url );
	}

	$url = add_query_arg( '_wpnonce', wp_create_nonce( 'h2_gravityform:' . $attrs['id'] ), $url );

	return sprintf(
		'<iframe src="%s" width="100%%" height="500" frameborder="0" scrolling="no" class="gfiframe"></iframe>',
		esc_url( $url )
	);
}

/**
 * Handle a Gravity Form request
 */
function handle_gravityform_request() {
	if ( empty( $_GET['h2_gravityform'] ) ) {
		return;
	}

	$id = absint( wp_unslash( $_GET['h2_gravityform'] ) );
	// phpcs:ignore HM.Security.ValidatedSanitizedInput.InputNotSanitized
	$nonce = wp_unslash( $_GET['_wpnonce'] ?? '' );
	if ( empty( $nonce ) || ! wp_verify_nonce( $nonce, 'h2_gravityform:' . $id ) ) {
		wp_die( 'Invalid nonce.' );
	}

	$options = [
		// phpcs:ignore HM.Security.ValidatedSanitizedInput.InputNotSanitized
		'title' => (bool) isset( $_GET['title'] ) ? wp_unslash( $_GET['title'] ) : false,
		// phpcs:ignore HM.Security.ValidatedSanitizedInput.InputNotSanitized
		'description' => (bool) isset( $_GET['description'] ) ? wp_unslash( $_GET['description'] ) : false,
	];

	render_gravityform( $id, $options );
	exit;
}

/**
 * Render a Gravity Form.
 *
 * @param int   $id      Form ID
 * @param array $options Form options for embedding
 */
function render_gravityform( int $id, array $options ) {
	add_filter( 'show_admin_bar', '__return_false', 100 );

	require_once( GFCommon::get_base_path() . '/form_display.php' );

	$form = GFFormsModel::get_form_meta( $id );

	echo '<!DOCTYPE html><html><head><meta charset="utf-8">';
	printf( '<title>%s</title>', esc_html( $form['title'] ) );
	wp_head();
	do_action( 'gfiframe_head', $id, $form );

	echo '</head><body><div class="PostContent">';

	GFFormDisplay::print_form_scripts( $form, false );
	gravity_form( $id, $options['title'], $options['description'] );
	wp_footer();

	echo '</div></body></html>';
}

/**
 * Force todo-list-block blocks to render on the frontend.
 *
 * See also _compat.scss.
 *
 * @param string $block_content The block content about to be appended.
 * @param array  $block         The full block, including name and attributes.
 * @return string Rendered block string.
 */
function render_todo_list_block( string $block_content, array $block ) : string {
	if ( $block['blockName'] !== 'tabor/todo-list' || empty( $block['innerBlocks'] ) ) {
		return $block_content;
	}

	ob_start();

	echo '<ul class="Tasklist">';
	foreach ( $block['innerBlocks'] as $list_item ) {
		printf(
			'<li class="Tasklist-Item" %s>%s</li>',
			// phpcs:ignore -- The output is a static string.
			( $list_item['attrs']['checked'] ?? false ) ? 'data-checked=""' : '',
			wp_kses_post( $list_item['attrs']['content'] )
		);
	}
	echo '</ul>';

	return (string) ob_get_clean();
}
